### ISSUE TITLE
how to train this model?

### ISSUE THREAD

**Issue by carry-xz** [gengyanlei/Pytorch_Retinaface#1]
nice work! Is it  re-annotates the Wider Face dataset and retrains the three branches model ?

**Comment by gengyanlei** [comment]
@carry-xz 
1. 采用hopenet预训练模型，在widerface的基础上，为每个人类作姿态估计label标注
2. 借鉴refer口罩分支检测的思路，没有作loss上面的改动，只是单纯的在数据上合并，加mosaic，网络分支修改等简单操作罢了。
