### ISSUE TITLE
请问有机会发出训练代码吗？

### ISSUE THREAD

**Issue by wanyne-yyds** [gengyanlei/Pytorch_Retinaface#5]

**Comment by gengyanlei** [comment]
@wanyne-yyds 
没有机会了，代码有bug未修复。

**Comment by wanyne-yyds** [comment]
> @wanyne-yyds 没有机会了，代码有bug未修复。

我在YOLOX训练出了能预测人脸与姿态角的，但会容易训崩。如果可以的话，可以看下你计算Loss那部分代码吗？

**Comment by gengyanlei** [comment]
我就是简单把[HopeNet-pytorch](https://github.com/natanielruiz/deep-head-pose)的损失拿过来根据人脸的检测复用了一下。

**Comment by wanyne-yyds** [comment]
> 我就是简单把[HopeNet-pytorch](https://github.com/natanielruiz/deep-head-pose)的损失拿过来根据人脸的检测复用了一下。

好的，谢谢哦
